filebeat.inputs:
  - type: log
    enabled: true
    tags: ["accounting"]
    paths:
      - /data/logs/*.log
    exclude_files: ['\.gz$']

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: "accounting-logs"
  codec.json:
    pretty: false
