global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'accounting'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['accounting:8082']
  - job_name: 'delivery'
    metrics_path: '/actuator/delivery'
    static_configs:
      - targets: [ 'delivery:8011' ]
  - job_name: 'kitchen'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'kitchen:8012' ]